#!/bin/sh

genobjs () {
	obj="build/${s%.*}"
	bin="build/${s%.*}.bin"
	echo "${obj}: ops/common.h"			>> deps.mk
	echo "${obj}: ${s}" 				>> deps.mk
	echo "	\$($compile) \$< -o \$@"		>> deps.mk
	echo "${bin}: lib/prune"			>> deps.mk
	echo "${bin}: ${obj}"				>> deps.mk
	echo "	\$(OBJCOPY) -j .text -Obinary \$< \$@"	>> deps.mk
	echo "	./lib/prune lib/empty.bin ${bin}"	>> deps.mk
	echo "${bin}"
}

case "${1}" in
	--ops)
		compile=OP_COMPILE
		;;

	--imms)
		compile=IMM_COMPILE
		;;
esac

mkdir -p $(echo "${2}" | xargs dirname | uniq | sed 's|^|build/|g')

for s in ${2}
do
	genobjs
done
